template: |
  ## Changes
  
  $CHANGES

name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
version-template: "$COMPLETE"

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&#@'

include-labels:
  - 'release'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: 'Maintenance'
    label: 'chore'
