template: |
  ## Changes

  $CHANGES

name-template: "next-v$RESOLVED_VERSION testing"
tag-template: "next-v$RESOLVED_VERSION"
tag-prefix: "next-v"

version-template: "$COMPLETE"

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&#@`'

include-labels:
  - 'release/next'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
