FROM postgres:15

WORKDIR /docker-entrypoint-initdb.d/

COPY <<load.sh /docker-entrypoint-initdb.d/
#!/bin/bash
set -x
ls ${PWD} | xargs -I% psql postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-localhost}:${POSTGRES_PORT:-5432}${POSTGRES_DB:-postgres} < %
load.sh

RUN chmod +x /docker-entrypoint-initdb.d/load.sh

COPY ./src/api-db-migrations/ /docker-entrypoint-initdb.d/

CMD ["/docker-entrypoint-initdb.d/load.sh"]
