FROM postgres:15

WORKDIR /docker-entrypoint-initdb.d/

COPY <<load.sh /docker-entrypoint-initdb.d/
#!/bin/bash
set -x
ls /docker-entrypoint-initdb.d/*.sql | xargs -I% psql ${CONNECTION_STRING_RW} < %
load.sh

RUN chmod +x /docker-entrypoint-initdb.d/load.sh

COPY ./src/api-db-migrations/ /docker-entrypoint-initdb.d/

CMD ["/docker-entrypoint-initdb.d/load.sh"]
