-- migrate:up

ALTER TABLE "SurveyData" OWNER TO "${POSTGRES_USER}";
ALTER TABLE "BaliVillage" OWNER TO "${POSTGRES_USER}";

GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_DB}" TO "${POSTGRES_USER}";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "${POSTGRES_USER}";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "${POSTGRES_USER}";

-- migrate:down
