name: Images

on:
  push:
    branches:
    - main
    - next
    - dev
    paths-ignore:
    - "Dockerfile.migrations"
    - "src/api-db-migrations/**"
    - ".github/workflows/build-push.migrations.yml"

jobs:
  call-build-and-push:
    name: Call
    uses: CirclesUBI/.github/.github/workflows/build-and-push.yml@main
    with:
      image-name: "api-server"
    secrets: inherit
