name: Extensions

on:
  release:
    types: [published]
  push:
    branches:
    - main
    - next
    - dev
    paths:
    - "Dockerfile.extensions"
    - "src/api-db-extensions/**"
    - ".github/workflows/build-push.extensions.yml"
  workflow_call:
    inputs:
      ref:
        required: true
        type: String
        default: ${{ github.ref }}

jobs:
  call-build-and-push:
    name: Call image build
    uses: CirclesUBI/.github/.github/workflows/build-and-push.yml@main
    if: ( inputs.ref == 0 )
    with:
      image-name: "api-server-extensions"
      file: "Dockerfile.extensions"
    secrets: inherit
  call-build-and-push-ref:
    name: Call tagged image build
    uses: CirclesUBI/.github/.github/workflows/build-and-push.yml@main
    if: ( inputs.ref != 0 )
    with:
      image-name: "api-server-extensions"
      file: "Dockerfile.extensions"
      ref: ${{ inputs.ref }}
    secrets: inherit
