name: Build and push container images
run-name: '${{ github.ref_name }} api-server ${{ github.run_number }} @${{ github.actor_id }}'

on:
  push:
    branches:
    - main
    - next
    - dev
    paths-ignore:
    - "Dockerfile.migrations"
    - "src/api-db-migrations/**"
    - ".github/workflows/build-push.migrations.yml"

jobs:
  call-build-and-push:
    name: Call
    uses: CirclesUBI/.github/.github/workflows/build-and-push.yml@0e374eae30ef5963869cfb6a0b5f7f68864248af
    with:
      image-name: "api-server"
    secrets: inherit
