name: Extensions

on:
  release:
    types: [published]
  push:
    branches:
    - main
    - next
    - dev
    paths:
    - "Dockerfile.extensions"
    - "src/api-db-extensions/**"
    - ".github/workflows/build-push.extensions.yml"

jobs:
  call-build-and-push:
    name: Call
    uses: CirclesUBI/.github/.github/workflows/build-and-push.yml@main
    with:
      image-name: "api-server-extensions"
      file: "Dockerfile.extensions"
    secrets: inherit
