name: Migrations

on:
  push:
    branches:
    - main
    - next
    - dev
    paths:
    - "Dockerfile.ncat"
    - ".github/workflows/build-push.ncat.yml"

jobs:
  call-build-and-push:
    name: Call
    uses: CirclesUBI/.github/.github/workflows/build-and-push.yml@main
    with:
      image-name: "api-server-ncat"
      file: "Dockerfile.ncat"
    secrets: inherit
