name: Build and push migrations container images
run-name: '${{ github.ref_name }} api-server-migrations ${{ github.run_number }} @${{ github.actor }}'

on:
  push:
    branches:
    - main
    - next
    - dev
    paths:
    - "Dockerfile.migrations"
    - "src/api-db-migrations/**"
    - ".github/workflows/build-push.migrations.yml"

jobs:
  call-build-and-push:
    name: Call
    uses: CirclesUBI/.github/.github/workflows/build-and-push.yml@d15d8aa3ecc09ca1bcac11e997b0192e33e3017d
    with:
      image-name: "api-server-migrations"
      file: "Dockerfile.migrations"
    secrets: inherit
