name: Build and push the database migrations container

on:
  push:
    branches: [ dev ]
    paths: [ "src/api-db-migrations/**" ]

jobs:
  call-build-and-push:
    name: Trigger container build and push
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/build-and-push-dockerfile.yml
    with:
      ref: "${{ github.ref }}"
      image: "api-server-db-migrations"
      file: "Dockerfile.init"
    secrets: inherit
