name: Detect and tag new version

on:
  push:
    branches:
      - 'main'
      - 'next'
      - 'dev'

jobs:
  tag-new-versions:
    name: Tag new version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
  release-new-versions:
    name: Trigger release
    uses: ./.github/workflows/release-drafter.yml
    secrets: inherit
