name: (dev) migrate database
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Build
        run: ./deploy_prisma.sh
        env:
          DO_PGSQL_CONNECTIONSTRING: ${{ secrets.DEV_DO_PGSQL_CONNECTIONSTRING }}
