name: Build and push the database migrations container

on:
  push:
    branches: [ dev ]
    paths:
    - "Dockerfile.migrations"
    - "src/api-db-migrations/**"

jobs:
  call-build-and-push:
    name: Trigger container build and push from database migrations Dockerfile
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/build-and-push-dockerfile.yml
    with:
      image: "api-server-migrations"
      file: "Dockerfile.migrations"
    secrets: inherit
