name: Build and push the dev image

on:
  push:
    branches: [ dev ]
    paths-ignore:
    - "Dockerfile.migrations"
    - "src/api-db-migrations/**"
    - ".github/workflows/*-migrations.yml"
    - ".github/workflows/build-and-push-dockerfile.yml"

jobs:
  call-build-and-push:
    name: Trigger container build and push
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/build-and-push.yml
    secrets: inherit
