name: (main) migrate database
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Build
        run: ./deploy_prisma.sh
        env:
          DO_PGSQL_CONNECTIONSTRING: ${{ secrets.DO_PGSQL_CONNECTIONSTRING }}
