name: Build and push the next image

on:
  push:
    branches: [ next ]
    paths-ignore:
    - "Dockerfile.migrations"
    - "src/api-db-migrations/**"
    - ".github/workflows/*-migrations.yml"
    - ".github/workflows/build-and-push-dockerfile.yml"

jobs:
  call-build-and-push:
    name: Call
    uses: CirclesUBI/.github/.github/workflows/build-and-push.yml@0e374eae30ef5963869cfb6a0b5f7f68864248af
    with:
      image-name: "api-server"
    secrets: inherit
