name: Release Next

on:
  push:
    branches:
      - next

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "next"
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.next.yml
          disable-autolabeler: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
